name: Java CI

on:
  push:
  pull_request:
    branches:
      - main
jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: test
      run: go test ./frontend/